### ISSUE TITLE
Unable to connect Cinnamon IR.

### ISSUE THREAD

**Issue by AllanCat** [seraxis/lr2oraja-endlessdream#11]
Version: 0.1.1
When launching lr2oraja, console log shown:
[Cinnamon IR] (0.2.0) GET request to https://ir.api.cinnamon.link/v1/users/me
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asBoolean()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
12月 30, 2023 11:22:31 下午 bms.player.beatoraja.MainController <init>
警告: IR??????失敗 : Internal Exception

This issue doesn't occur to original lr2oraja from wcko87.
Note that Bokutachi IR works fine with 0.1.1, so I'm not sure if it's 0.1.1's issue or Cinnamon IR's issue.

**Comment by seraxis** [comment]
I will look into this but Endless Dream isn't tested with Cinnamon IR, some of the features Endless Dream implements (the random trainer) may be against the spirit of the rules for Cinnamon IR. first,

All changes that could effect the IR that are made to Endless Dream are cleared with Bokutachi (the de-facto western lr2oraja IR) first, so you could consider that to be Endless Dream's only officially supported IR

**Comment by MatVeiQaaa** [comment]
Cinnamon IR expects one of the allowed version names in bms.player.beatoraja.MainController.VERSION variable. "LR2oraja Endless Dream 0.1.1" is not one of them.

**Comment by seraxis** [comment]
differentiating the version variable here might be a positive, as I have no confirmation as to whether or not Cinnamon approves of the changes this fork makes wrt score submission of fixed randoms. Closing as this isn't an issue with Endless Dream
