### ISSUE TITLE
Game fails to launch due to... Missing font in default skin?

### ISSUE THREAD

**Issue by AkiraMorilas** [seraxis/lr2oraja-endlessdream#14]
I'm assuming there's something more involved in here because surely this would've been noticed by someone by now(unless nobody tried this game on linux yet).
![Screenshot_20240112_211641](https://github.com/seraxis/lr2oraja-endlessdream/assets/134231050/0b4bd398-5ad7-40b8-a0a9-1494da4edd2f)
openSUSE Tumbleweed, up to date, using bellsoft-java8-full with LibericaFX, game version 0.1.1

**Comment by marysiamzawka** [comment]
Have you installed Endless Dream over a stock install of beatoraja? You need to start off with [any version that isn't the bare .jar file](https://www.mocha-repository.info/download.php)

**Comment by AkiraMorilas** [comment]
That helped, thanks

**Comment by marysiamzawka** [comment]
No probs.
You can close the issue now
